# Generated by Django 3.2.21 on 2023-09-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangmanApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_to_guess', models.CharField(max_length=100)),
                ('current_word_state', models.CharField(max_length=100)),
                ('incorrect_guesses', models.PositiveIntegerField(default=0)),
                ('max_incorrect_guesses', models.PositiveIntegerField(default=0)),
                ('game_state', models.CharField(default='InProgress', max_length=20)),
            ],
        ),
    ]
